# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yogendra Bahadur Shrestha
email: id_ybs@hotmail.com
description: This is my personal website from codecademy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yogendrabs.github.io" # the base hostname & protocol for your site
twitter_username: no twitter account :(
github_username:  yogendrabs

# Build settings
markdown: kramdown
